name: 'GitHub Actions Weather Bot'

on:
  watch:
    types: started
  schedule:
 ##   - cron: '0 21 * * *'  ##暂时取消运行

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shenzhen' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shenzhen Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: 2679225466@qq.com
          from: GitHub Actions
          content_type: text/html
